### ISSUE TITLE
Devhub Issue: Persistent Storage Services:  no Netapp docs

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/openshift-wiki#49]
> path: (do not delete) https://github.com/BCDevOps/openshift-wiki/blob/master/docs/OCP/OCPStorageServices.md
 > (do not delete) devhub page: undefined

## Devhub Content Issue

This document is not clear on guidance for using netapp. It should also make it VERY clear that gluster can no longer be provisioned

**Comment by jefkel** [comment]
Your conclusion that gluster can no longer be provisioned is incorrect.  I'm not sure what guidance you're looking for on using netapp storageclasses.

Gluster is supported as provision-able storage on the platform.  Due to capacity issues (ie: the gluster storage was filling up), we have another set of storageClasses available for provisioning (NetApp) and have reduced storage quota in gluster.  However it is not a requirement to migrate existing storage, and at some point, additional quota on that platform may become available.

**Comment by patricksimonian** [comment]
This isn't for me. I have had issues of deployments failing when attempting to reprovision gluster. Could this be another issue. Sorry to say I don't have many other details at this time. It was when I was troubleshooting redeploying things like Matomo and or Jenkins
